spring:
 profiles:
  active:
   - dev
---
server:
 port: 7001 # 注册中心占用7001端口，冒号后面必须有空格

spring:
 profiles: dev
 application:
  name: myapp-eureka-client

eureka:
 instance:
  hostname: eureka7001.com 
 client:
  register-with-eureka: false # 当前的 eureka-server 自己不注册进服务列表中
  fetch-registry: false       # 不通过 eureka 获取注册信息
  service-url:
   defaultZone: http://sqq:7001/eureka/
---
server:
 port: 7001 # 注册中心占用7001端口，冒号后面必须有空格

spring:
 profiles: prod
 application:
  name: myapp-eureka-client

eureka:
 instance:
  hostname: eureka7001.com 
 client:
  register-with-eureka: false # 当前的 eureka-server 自己不注册进服务列表中
  fetch-registry: false       # 不通过 eureka 获取注册信息
  service-url:
   defaultZone: http://sqq:7001/eureka/
