spring:
 profiles:
  active:
   - dev
---
server:
 port: 7003 # 注册中心占用7001端口，冒号后面必须有空格

spring:
 profiles: dev
 application:
   name: myapp-eureka-client   # eureka 服务端的实例名称

eureka:
 instance:
  hostname: eureka7003.com 
 client:
  register-with-eureka: false # 当前的 eureka-server 自己不注册进服务列表中
  fetch-registry: false       # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
  service-url:
   defaultZone: http://sqq:7001/eureka/, http://sqq:7002/eureka/
---
server:
 port: 7003 # 注册中心占用7001端口，冒号后面必须有空格

spring:
 profiles: prod
 application:
   name: myapp-eureka-client   # eureka 服务端的实例名称

eureka:
 instance:
  hostname: eureka7003.com    # eureka 服务端的实例名称 
 client:
  register-with-eureka: false # 当前的 eureka-server 自己不注册进服务列表中
  fetch-registry: false        # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
  service-url:
   defaultZone: http://sqq:7001/eureka/, http://sqq:7002/eureka/
